### ISSUE TITLE
Add Restriction For User

### ISSUE THREAD

**Issue by ninadvyas** [ninadvyas/All-Recipe#1]
Restrict users from searching for anything unrelated to cooking. If a user tries to search for non-cooking content, a warning message should be displayed to inform them that only cooking-related searches are allowed.

#### Acceptance Criteria:

- Users can only search for cooking-related content.
- If a user tries to search for non-cooking-related terms, a warning should be shown (e.g., "Only cooking-related searches are allowed. Please refine your search.").

**Comment by JyotDhamelia** [comment]
hello ninad, i want to  work on this issue please assign it to me

**Comment by JyotDhamelia** [comment]
Hi @ninadvyas i would love to work on this issue. Can you please assign this issue to me ?
