### ISSUE TITLE
Change Website Theme

### ISSUE THREAD

**Issue by ninadvyas** [ninadvyas/All-Recipe#2]
Update the website's theme to use a green color contrast as the primary color scheme. This will involve adjusting the color palette of the website to focus on shades of green for backgrounds, text, buttons, and other UI components.

Acceptance Criteria:

- Replace the current primary color scheme with shades of green.
- Ensure all buttons, links, and interactive elements reflect the new green theme.
- Backgrounds and text colors should contrast well with the green theme to maintain readability and accessibility (follow WCAG guidelines).
- Update hover states, focus states, and active states of buttons and links to match the new theme.

**Comment by JyotDhamelia** [comment]
i have done all the task please review it

**Comment by JyotDhamelia** [comment]
i have done all the tasks please review it
